import { NextResponse } from "next/server";
import { connectDB } from "@/lib/mongodb";
import Project from "@/models/Project";


// GET: Retrieve all projects from the cluster
export async function GET() {
  try {
    await connectDB();
    const projects = await Project.find({}).sort({ createdAt: -1 });
    return NextResponse.json({ success: true, data: projects }, { status: 200 });
  } catch (error) {
    return NextResponse.json({ success: false, error: error.message }, { status: 500 });
  }
}

// POST: Add a new project from your frontend creation modal

export async function POST(request) {
  try {
    await connectDB();
    const body = await request.json();

    // 1. Validate required fields before database operation
    const { projectName, category, initialStatus, clientPartner, budgetAllocation } = body;

    if (!projectName || !category || !clientPartner) {
      return NextResponse.json(
        { success: false, error: "Missing required fields: projectName, category, and clientPartner are mandatory." },
        { status: 422 }
      );
    }

    // 2. Map fields directly to match the upgraded Schema
    const newProject = await Project.create({
      projectName,
      category,
      // Fallback to initialStatus if sent from old client frontend payload
      initialStatus,
      clientPartner,
      budgetAllocation: Number(budgetAllocation) || 0,
      // Note: projectId is automatically generated by the pre-validate hook in the model
    });

    return NextResponse.json(
      {
        success: true,
        message: "Project successfully created!",
        data: {
          id: newProject._id,
          projectId: newProject.projectId, // Returns PRJ0001, PRJ0002, etc.
          projectName: newProject.projectName,
          category: newProject.category,
          initialStatus:newProject.initialStatus,
          clientPartner: newProject.clientPartner,
          budgetAllocation: newProject.budgetAllocation,
          createdAt: newProject.createdAt,
        },
      },
      { status: 201 }
    );
  } catch (error) {
    // Handle Mongoose duplicate key errors (e.g., if custom projectId collides)
    if (error.code === 11000) {
      return NextResponse.json(
        { success: false, error: "A project with this generated ID already exists. Please retry." },
        { status: 409 }
      );
    }

    // Handle Mongoose Schema Validation Errors
    if (error.name === "ValidationError") {
      const messages = Object.values(error.errors).map((val) => val.message);
      return NextResponse.json(
        { success: false, error: messages.join(", ") },
        { status: 400 }
      );
    }

    return NextResponse.json(
      { success: false, error: error.message || "Internal Server Error" },
      { status: 500 }
    );
  }
}